name       : python-mistune
version    : 0.8.3
release    : 6
source     :
    - https://github.com/lepture/mistune/archive/v0.8.3.tar.gz : 666c93fc10cb0aa924a373898a709eba4d43f4e453264a4c7396878ec8145a4a
license    : BSD-3-Clause
component  : programming.python
summary    : The fastest markdown parser in pure Python with renderer feature.
description: |
    The fastest markdown parser in pure Python with renderer feature.
builddeps  :
    - cython
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
