name       : python-mistune
version    : 0.8.4
release    : 10
source     :
    - https://github.com/lepture/mistune/archive/v0.8.4.tar.gz : a1443771ea9ed7268a0cb3cf31462604ae148938ba32070bd5c54545f8f36a5d
homepage   : https://github.com/lepture/mistune
license    : BSD-3-Clause
component  : programming.python
summary    : The fastest markdown parser in pure Python with renderer feature
description: |
    The fastest markdown parser in pure Python with renderer feature.
builddeps  :
    - cython
    - python-nose
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
