name       : python-mistune
version    : '0.8'
release    : 2
source     :
    - https://github.com/lepture/mistune/archive/v0.8.tar.gz : f479dc2ceac7d593231e77448cb5cf7194fdbebad1d88fcdb78eacac1c042f6e
license    : BSD-3-Clause
component  : programming.python
summary    : The fastest markdown parser in pure Python with renderer feature.
description: |
    The fastest markdown parser in pure Python with renderer feature.
builddeps  :
    - cython
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
