name       : python-mistune
version    : 0.8.1
release    : 3
source     :
    - https://github.com/lepture/mistune/archive/v0.8.1.tar.gz : 77ae24a5accfd62d23f945d7e6598392194f8ca6ef1bd70ddc81e151ac3eb1fe
license    : BSD-3-Clause
component  : programming.python
summary    : The fastest markdown parser in pure Python with renderer feature.
description: |
    The fastest markdown parser in pure Python with renderer feature.
builddeps  :
    - cython
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
