name       : python-mistune
version    : 2.0.4
release    : 11
source     :
    - https://files.pythonhosted.org/packages/source/m/mistune/mistune-2.0.4.tar.gz : 9ee0a66053e2267aba772c71e06891fa8f1af6d4b01d5e84e267b4570d4d9808
homepage   : https://github.com/lepture/mistune
license    : BSD-3-Clause
component  : programming.python
summary    : A sane Markdown parser with useful plugins and renderers
description: |
    A fast yet powerful Python Markdown parser with renderers and plugins.
builddeps  :
    - cython
    - python-build
    - python-installer
    - python-packaging
    - python-pytest
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
